"""rename text_url -> text

Revision ID: cc2953c2dec9
Revises: c6dbc0f93e18
Create Date: 2025-12-16 23:14:34.610539

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cc2953c2dec9'
down_revision: str | Sequence[str] | None = 'c6dbc0f93e18'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lectures', sa.Column('text', sa.Text(), nullable=True))
    op.drop_column('lectures', 'text_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lectures', sa.Column('text_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('lectures', 'text')
    # ### end Alembic commands ###
